In [2]:
import pandas as pd

In [8]:
#Import July Dataset
july = pd.read_csv("./202307-citibike-tripdata.csv")
july.head()

/var/folders/xc/r18gm2sd0m16qw4wsywkh69w0000gn/T/ipykernel_18956/533149840.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  july = pd.read_csv("./202307-citibike-tripdata.csv")

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,BC78328130CD8A16,classic_bike,2023-07-16 20:42:57,2023-07-16 20:45:13,St. Nicholas Ave & W 126 St,7756.10,Adam Clayton Powell Blvd & W 126 St,7738.04,40.811432,-73.951878,40.809495,-73.947765,member
1,71A4DFA231ADAEA2,classic_bike,2023-07-29 12:22:21,2023-07-29 12:26:54,Adam Clayton Powell Blvd & W 118 St,7670.09,Adam Clayton Powell Blvd & W 126 St,7738.04,40.804372,-73.951475,40.809495,-73.947765,member
2,B64451D0D9F52134,classic_bike,2023-07-30 18:30:18,2023-07-30 18:35:42,St. Nicholas Ave & W 126 St,7756.10,Lenox Ave & W 130 St,7753.13,40.811378,-73.951827,40.810792,-73.943068,member
3,EEECB3E0E05EB0DB,classic_bike,2023-07-04 19:59:20,2023-07-04 20:02:03,St. Nicholas Ave & W 126 St,7756.10,Adam Clayton Powell Blvd & W 126 St,7738.04,40.811432,-73.951878,40.809495,-73.947765,member
4,76B706DF4FC180DC,classic_bike,2023-07-03 19:33:36,2023-07-03 19:43:59,St. Nicholas Ave & W 126 St,7756.10,Pleasant Ave & E 116 St,7450.05,40.811543,-73.951813,40.794988,-73.933335,member

In [9]:
#Import August Dataset
august = pd.read_csv("./202308-citibike-tripdata.csv")
august.head()

/var/folders/xc/r18gm2sd0m16qw4wsywkh69w0000gn/T/ipykernel_18956/1754768907.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  august = pd.read_csv("./202308-citibike-tripdata.csv")

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,C5E94016E7939757,classic_bike,2023-08-29 21:15:27,2023-08-29 21:51:04,Lexington Ave & E 36 St,6313.10,Amsterdam Ave & W 125 St,7800.03,40.747574,-73.978801,40.813358,-73.956461,member
1,E88D94798ABBBD7C,classic_bike,2023-08-06 19:03:35,2023-08-06 19:04:56,Rockaway Ave & Bainbridge St,4285.09,MacDougal St & Rockaway Ave,4212.01,40.683236,-73.911943,40.680180,-73.911360,member
2,341D3CE4743A92EC,classic_bike,2023-08-02 20:34:04,2023-08-02 20:40:19,W 13 St & 5 Ave,5947.04,E 10 St & 2 Ave,5746.02,40.735445,-73.994310,40.729708,-73.986598,member
3,21C763DECA96FD02,classic_bike,2023-08-14 13:47:23,2023-08-14 14:17:36,Central Park North & Adam Clayton Powell Blvd,7617.07,5 Ave & E 29 St,6248.06,40.799484,-73.955613,40.745168,-73.986831,member
4,A8533C28598A6AB8,classic_bike,2023-08-03 13:05:09,2023-08-03 13:52:27,W 13 St & 5 Ave,5947.04,Amsterdam Ave & W 125 St,7800.03,40.735445,-73.994310,40.813358,-73.956461,member

In [10]:
#Import September Dataset
september = pd.read_csv("./202309-citibike-tripdata.csv")
september.head()

/var/folders/xc/r18gm2sd0m16qw4wsywkh69w0000gn/T/ipykernel_18956/2158339777.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  september = pd.read_csv("./202309-citibike-tripdata.csv")

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,B0A0F1DEFA4B72FC,electric_bike,2023-09-03 10:20:41,2023-09-03 10:24:16,E 1 St & Bowery,5636.13,E 10 St & 2 Ave,5746.02,40.724861,-73.992131,40.729708,-73.986598,member
1,2B26AB15647BF4EE,classic_bike,2023-09-27 15:44:23,2023-09-27 15:53:25,Pearl St & Hanover Square,4993.02,Allen St & Rivington St,5414.06,40.704650,-74.009133,40.720196,-73.989978,member
2,9D2B5971CA4E513F,classic_bike,2023-09-19 13:40:48,2023-09-19 13:48:11,E 1 St & Bowery,5636.13,E 10 St & 2 Ave,5746.02,40.724753,-73.992116,40.729708,-73.986598,member
3,17E6760596DC3ABE,classic_bike,2023-09-30 16:27:50,2023-09-30 16:56:35,Central Ave & Himrod St,4713.01,Mott St & Prince St,5561.04,40.696706,-73.922935,40.723180,-73.994800,member
4,97EFF376A7E2DC70,classic_bike,2023-09-21 16:59:53,2023-09-21 17:07:36,St Marks Pl & 2 Ave,5669.10,Mott St & Prince St,5561.04,40.728419,-73.987140,40.723180,-73.994800,member

In [11]:
#Combine All Datasets
combined_months = pd.concat([july, august, september], axis=0, ignore_index=True)

In [12]:
#Export Dataset to CSV
combined_months.to_csv('combined_months.csv', index=False)